apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpe-media-service.fullname" . }}-config
data:
  PORT: {{ .Values.port | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  MAX_FILE_SIZE: {{ .Values.maxFileSize | quote }}
  ALLOWED_IMAGE_TYPES: {{ .Values.allowedImageTypes | quote }}
  AWS_REGION: {{ .Values.awsRegion | quote }}
  AWS_S3_BUCKET: {{ .Values.awsS3Bucket | quote }}