apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpe-media-service.fullname" . }}
  labels:
    app: {{ include "gpe-media-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "gpe-media-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gpe-media-service.name" . }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ include "gpe-media-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "gpe-media-service.fullname" . }}-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "gpe-media-service.fullname" . }}-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gpe-media-service.fullname" . }}-config
                  key: AWS_REGION
            - name: AWS_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gpe-media-service.fullname" . }}-config
                  key: AWS_S3_BUCKET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gpe-media-service.fullname" . }}-config
                  key: PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gpe-media-service.fullname" . }}-config
                  key: LOG_LEVEL
            - name: MAX_FILE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gpe-media-service.fullname" . }}-config
                  key: MAX_FILE_SIZE
            - name: ALLOWED_IMAGE_TYPES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gpe-media-service.fullname" . }}-config
                  key: ALLOWED_IMAGE_TYPES
          ports:
            - containerPort: {{ .Values.port | default 3000 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}