apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpe-media-service.fullname" . }}-mux-secret
type: Opaque
data:
  tokenId: {{ .Values.mux.tokenId   | b64enc }}
  tokenSecret: {{ .Values.mux.tokenSecret | b64enc }}
  webhookSecret: {{ .Values.mux.webhookSecret | b64enc }}
