apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpe-media-service.fullname" . }}-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyId | default "" | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | default "" | b64enc | quote }}