apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpe-media-service.fullname" . }}
  labels:
    app: {{ include "gpe-media-service.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default .Values.port | default 3000 }}
      targetPort: {{ .Values.port | default 3000 }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "gpe-media-service.name" . }}